version: '3.8'

services:
  fcrepo:
    image: fcrepo/fcrepo
    container_name: fcrepo
    ports:
      - "8080:8080"
    environment:
      - FCREPO_LOG_LEVEL=INFO
    volumes:
      - fcrepo_data:/data

  php:
    image: php:8.0-cli
    container_name: php
    volumes:
      - ./php-app:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: php -S 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  fcrepo_data:
