version: '3.8'

services:
  fcrepo:
    image: fcrepo/fcrepo
    container_name: fcrepo
    ports:
      - "8080:8080"
    environment:
      - FCREPO_LOG_LEVEL=INFO
    volumes:
      - fcrepo_data:/data

  fedora-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fedora-php
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null
    depends_on:
      - fcrepo

volumes:
  fcrepo_data:
